#!/usr/bin/env python3
from ev3dev2.motor import MoveTank, OUTPUT_A, OUTPUT_B
from time import sleep
from ev3dev2.button import Button

btn = Button()
tank_pair = MoveTank(OUTPUT_A, OUTPUT_B)

while not btn.any():
    x=input("Press arrow keys")
    if x=='f':
        tank_pair.on(left_speed=0, right_speed=0)
        tank_pair.on(left_speed = 50, right_speed = 50)
    elif x=='b':
        tank_pair.on(left_speed=0, right_speed=0)
        tank_pair.on(left_speed=-50, right_speed=-50)
    elif x=='l':
        tank_pair.on(left_speed=0, right_speed=0)
        tank_pair.on(left_speed=0, right_speed=35)
    elif x=='r':
        tank_pair.on(left_speed=0, right_speed=0)
        tank_pair.on(left_speed=35, right_speed=0)
    elif x=='s':
        tank_pair.on(left_speed=0, right_speed=0)
        break

